name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '1 00,12 * * *' # Runs at 00:01 and 12:01
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://tahaben.com.ly/feed/"
